default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: crypto_rails
  password: crypto_rails_pass
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crypto_rails_development

test:
  <<: *default
  database: passenger_app_test

production:
  <<: *default
  database: crypto_rails_development
  username: crypto_rails
  password: crypto_rails_pass